EUCLIDEANDISTANCE_CC = gcc

EUCLIDEANDISTANCE_CFLAGS += -IC/include 

EUCLIDEANDISTANCE_SRC = C/src/Vecotr/vector.c C/src/Vector/benchmark.c

EUCLIDEANDISTANCE_TEST_SRC = C/tests/vector_test/benchmarks/eucdist_bench.c

EUCLIDEANDISTANCE_TARGET = euclidean_distance

euclideand:
	$(EUCLIDEANDISTANCE_CC) $(EUCLIDEANDISTANCE_CFLAGS) $(EUCLIDEANDISTANCE_SRC) $(EUCLIDEANDISTANCE_TEST_SRC) -o $(EUCLIDEANDISTANCE_TARGET)


euclideand_run:
	./$(EUCLIDEANDISTANCE_TARGET)