EUCLIDEANDISTANCE_CC = gcc

EUCLIDEANDISTANCE_CFLAGS = -IC/INCLUDE 

EUCLIDEANDISTANCE_SRC = C/src/vector.c C/src/benchmark.c

EUCLIDEANDISTANCE_TEST_SRC = C/tests/vector_test/benchmarks/eucdist_bench.c

EUCLIDEANDISTANCE_TARGET = euclidean_distance

euclideand:
	$(EUCLIDEANDISTANCE_CC) $(EUCLIDEANDISTANCE_SRC) $(EUCLIDEANDISTANCE_TEST_SRC) $(EUCLIDEANDISTANCE_CFLAGS) -o $(EUCLIDEANDISTANCE_TARGET)


euclideand_run:
	./$(EUCLIDEANDISTANCE_TARGET)